# Generated by Django 5.2.6 on 2026-01-28 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_resident_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='PENDING', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(help_text='Ex. Living Room, Kitchen', max_length=100)),
                ('analysis_json', models.JSONField(blank=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to='users.resident')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('issue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='issues.issue')),
                ('category', models.CharField(choices=[('NOISE', 'Noise Disturbance'), ('SMELL', 'Unpleasant Smell'), ('PARKING', 'Illegal Parking'), ('OTHER', 'Other')], max_length=50)),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='complaints/')),
            ],
            bases=('issues.issue',),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('issue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='issues.issue')),
                ('equipment_type', models.CharField(help_text='Ex. Air Conditioner, Pipe', max_length=100)),
                ('appointment_date', models.DateTimeField(blank=True, null=True)),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='maintenance/before/')),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='maintenance/after/')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='users.technician')),
            ],
            bases=('issues.issue',),
        ),
    ]
