# Generated by Django 6.0.2 on 2026-02-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('OVERDUE', 'Overdue'), ('SUCCESS', 'SUCCESS')], default='PENDING', max_length=20),
        ),
    ]
