# Generated by Django 6.0.2 on 2026-02-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_resident_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='is_on_duty',
            field=models.BooleanField(default=False, help_text='Status: On Duty or Off Duty'),
        ),
    ]
